<x-layouts.app>
<div class="bg-[#0019ff]">Ciao</div>
<div class="bg-sky-500">Test</div>
<div class="bg-[#272C4D]">Prova</div>
<div class="bg-[#45465A]">Dark</div>
<div class="h-20">Altezza</div>
<div class="bg-[#FF5F7E]">Registrati Button</div>
<div class="text-[#E2E8F0]"></div>
<div class="bg-[#E7E7E7]">New background</div>
<div class="bg-[#E6EBF7]">Section</div>
<div class="text-[#272C4D]">Testo primary</div>
<div class="text-gray-600">Testo subtitle</div>
<div class="text-[#FF5F7E]"></div>
<div class="hover:text-[#E2E8F0]">Provaaaa</div>
<div class="hover:underline underline-offset-[14]">Ciaoooooo</div>
<div class="lg:h-20 sm:h-12">Logo</div>
<div class="text-center sm:text-center">Testo centrato</div>
<div class="flex justify-around">Flex</div>
<div class="w-80 h-80 rounded-md flex justify-center items-center bg-[#272C4D]">Cards</div>
<div class="border-transparent">Border</div>
<div class="hover:text-[#FF5F7E]">Hover card</div>
<div class="bg-[#F9F9F9]">Card background</div>
<div class="hover:cursor-pointer">Cursor card</div>
<div class="mx-4">Margin left-right</div>
<div class="bg-[#EBF5FF]">Form background</div>
<div class="bg-[#2E9FBE]">New Primary</div>
<div class="text-[#2E9FBE]">Text new primary</div>
<div class="py-5">Padding 20px</div>
<div class="pb-5">Padding bottom 20px</div>
<div class="text-l">Testo large</div>
<div class="size-7">Size 7</div>
<div class="w-7 h-7">Width height</div>
<div class="flex-col">
    <div class="!bg-[#272C4D]"></div>
</div>
<div class="items-center">
    <div class="!bg-[#1A467F]"></div>
</div>
<div class="text-lg">Testo large</div>
<div class="mb-7">Padding bottom small</div>
<div class="!border-[#FF5F7E]">Border</div>
<div class="!bg-[#FF5F7E]">Background</div>
<div class="border-[#1A467F]">Border</div>
<div class="!border-black">BorderBlack</div>
<div class="mb-12">Margin bottom</div>
<div class="m-6">Margin</div>
<div class="w-96">Width</div>
<div class="bg-[#B9C3D1]"></div>
<div class="p-8">Padding</div>
<div class="mb-8">Marginnn</div>
<div class="!py-8">Padding zero</div>
<div class="bg-[#DBE3EE]">Background button azioni</div>
<div class="py-8">Padding Y</div>
<div class="m-12">Margin 12</div>
<div class="mx-0">Margin x</div>
<div class="bg-gradient-to-white from-[#1A467F]">Gradient</div>
<div class="h-96"></div>
<div class="w-[800px]">Width custom</div>
<div class="w-[450px]">Width calendario</div>
<div class="grid-cols-2"></div>
<div class="grid grid-cols-2 gap-4"></div>
<div class="h-auto"></div>
<div class="min-h-screen"></div>
<div class="m-5">Margin five</div>
<div class="px-3">Padding 3</div>
<div class="gap-4">Gap-4</div>
<div class="p-6"></div>
<div class="lg:w-[350px]">Logo width large</div>
<div class="w-[300px]">Width small</div>
<div class="bg-transparent"></div>
<div class="bg-gradient-to-r from-cyan-500 to-blue-500">gradiant</div>
<div class="bg-gradient-to-r from-cyan-500 to-[#272C4D]">gradient</div>
<div class="min-h-screen">screen height</div>
<div class="border-[#1A467F]"></div>
<div class="min-h-[50vh]">min height</div>
<div class="min-h-20 md:min-h-20">min heightt</div>
<div class="min-h-[700px]">min height costum</div>
<div class="w-[350px]">width 350</div>
<div class="w-[700px]">width 700px</div>
<div class="bg-[#F5F5F5]">background primary chiaro</div>
<div class="ring-[#FF5F7E]">ring primary</div>
<div class="focus:border-[#FF5F7E]">focus primary</div>
<div class="focus:ring-[#FF5F7E]">focus ring primary</div>
<div class="fixed top-0 left-0 right-0 z-50">header fixed</div>
<div class="mt-1.5">margin bottom header</div>
<div class="fixed top-0 left-0 right-0 z-50 h-24">fixed</div>
<div class="!fixed">fix</div>
<div class="w-[750px]">width 1000px</div>
<div class="w-[400px]">width 400px</div>
<div class="min-h-[600px]">min h 600px</div>
<div class="bg-[#B4E1BE]">background success</div>
<div class="text-[#3E783E]">text success</div>
<div class="bg-[#F38B8B]">backgroung error</div>
<div class="text-[#BF0303]">text error</div>
<div class="w-7/12">width 60%</div>
<div class="text-[#272C4D]"></div>
<div class="justify-evenly">justify evenly</div>
<div class="lg:w-7/12">large width calendar</div>
<div class="mt-9">margin top 9</div>
<div class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 hidden group-hover:block bg-gray-800 text-white text-sm px-2 py-1 rounded z-10">tooltip</div>
<div class="my-9">margin-top-bottom</div>
<div class="lg:w-3/12">large width 3/12</div>
<div class="lg:w-2/5">large width 2/5</div>
<div class="text-xs">testo small</div>
<div class="pr-1">padding right 1</div>
<div class="pr-5">padding right 5</div>
<div class="bg-[#D1DDEF]">background appuntamenti in entrata</div>
<div class="rounded-[15px]">border radius 15</div>
<div class="w-2/4">width 2/4</div>
<div class="py-9">padding y 9 </div>
<div class="bg-transparent">bg transparent</div>
<div class="bg-cover">bg cover</div>
<div class="bg-no-repeat">bg no repeat</div>
<div class="bg-center">bg center</div>
<div class="h-screen">height 100vh</div>
<div class="h-[95px]">height header</div>
<div class="bg-[url(/img/landing-salute-ora-final.svg')]">background-landing</div>
<div class="{{ bgClass }} bg-cover bg-no-repeat h-screen m-0 p-0">bg</div>
<div class="bg-[#DDE5EB]">background card rifiutati</div>
<div class="text-[#FCD5D0]">testo</div>
<div class="lg:w-3/6">large</div>
<div class="bg-[#C6E6CE]">background appuntamenti conclusi</div>
<div class="inset-0">index</div>
<div class="h-10">height logo mobile</div>
<div class="text-[45px]">testo titolo mobile</div>
<div class="lg:m-20">large margin</div>
<div class="border-slate-800">border</div>
<div class="border-[1px]">borderrr</div>
<div class="border-slate-500">border slate 600</div>
<div class="w-3/6">width input</div>
<div class="border-[#c5c5c5]">border grigio dati</div>
<div class="w-[500px]">width 500</div>
<div class="lg:flex-row">large flex-row</div>
<div class="min-h-[725px]">min h book</div>
<div class="lg:min-h-[725px]">large min height</div>
<div class="bg-[#E6EBF7D1]">background card registrazione</div>
<div class="rounded-[25px]">border card</div>
<div class="bg-[#E6EBF7B3]">background card opacity</div>
<div class="hover:py-5">hover button register</div>
<div class="hover:py-9">hoverrrrrrrrrrr</div>
<div class="flex-1">flex 1</div>
<div class="h-[100px]">height 100px</div>
<div class="lg:ml-5">large margin left</div>
<div class="h-52">height 208 px</div>
<div class="lg:min-h-36">large footer height</div>
<div class="left-[15%]">left 15%</div>
<div class="right-[15%]">right 15%</div>
<div class="mt-10">margin-top 10</div>
<div class="lg:py-8">large py-8</div>
<div class="text-[#F38B8B]">testo rosa chiaro</div>
<div class="mx-10">mx 10</div>
<div class="mx-24">mx 24</div>
<div class="mx-40">mx 40</div>
<div class="mx-56">mx 56</div>
<div class="mx-60">mx 60</div>
<div class="m-auto">mx auto</div>
<div class="ring-[#FF5F7E]">ring pink</div>
<div class="shadow-[0_10px_40px_rgba(0,0,0,0.2)]">shadow</div>
<div class="p-9">padding 9</div>
<div class="bg-[url('/img/inmp-logo-trasparenza.svg')]">bg inmp</div>
<div class="my-5">margin top bottom 5</div>
<div class="w-10/12">width 83%</div>
<div class="w-8/12">width 60%</div>
<div class="w-7/12">width 50%</div>
<div class="text-[40px]">testo 40px</div>
<div class="w-60 h-60">width e height 15rem</div>
<div class="lg:justify-evenly">large justify-evenly</div>
<div class="h-[125px]">height 125px</div>
<div class="leading-7"></div>
<div class="lg:h-40">large height inmp</div>
<div class="lg:h-28">large height coi</div>
<div class="w-[70%]">width 70%</div>
<div class="bg-[url('/img/landing-mobile-salute-orale.svg')]">bkg url</div>
<div class="bg-none">no bkg</div>
<div class="bg-[url('/img/landing-desktop-salute-orale.svg')]">bg desktop</div>
<div class="hidden">hidden</div>
<div class="md:hidden">md hidden</div>
<div class="h-dvh">height dvh</div>
<div class="transform origin-center scale-100 hover:scale-110 transition-transform duration-100">scale</div>
<div class="bg-transparent">transparent bkg</div>
<div class="bg-right-bottom">bg bot</div>
<div class="bg-right-top">bg right</div>
<div class="bg-none">bg none</div>
<div class="bg-[url('/img/desktop-salute-orale-landing.svg')]">bg nuovo</div>
<div class="w-dvw">w dvw</div>
<div class="bg-top">bg top</div>
<div class="bg-[url('/img/mobile-landing-salute-orale.svg')]">bg mobile</div>
<div class="lg:bg-[url('/img/soluzione-unita-desktop-landing.svg')]">bg desktop</div>
<div class="w-[60%]">width 60%</div>
<div class="ipad:bg-right-top">ipad bg position</div>
<div class="ipad:w-[40%]">width ipad</div>
<div class="ipad:text-4xl">ipad text</div>
<div class="ipad:ml-5">ipad margin left</div>
<div class="ipad:h-[50vh]">ipad height full</div>
<div class="ipad:w-3/4">ipad width full</div>
<div class="ipad:m-14">m 14</div>
<div class="ipad:flex-col">flex-col</div>
<div class="ipad:text-5xl">ipad text 4</div>
<div class="p-6">padding-6</div>
<div class="leading-8">leading</div>
<div class="lg:w-3/6">width 50%</div>
<div class="lg:hidden absolute top-full left-0 right-0 bg-black/95 backdrop-blur-md z-50 mx-2 mt-2 rounded-xl shadow-2xl border border-white/10">menu mobile blur</div>
<div class="bg-[#ff5f7e75]">bg transparent</div>
<div class="bg-[url('/img/soluzione-unita-per-desktop.svg')]">bg soluzione unita</div>
<div class="bg-[#272c4dd6]">bg</div>
<div class="p-4">p 4</div>
<div class="ipad:mt-60">mt 28 ipad</div>
</x-layouts.app>
